# -*- coding: utf-8 -*-
"""contCaracterRecursivo.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13YGksQVtTOtUd9dcbwwV1PEEJUIUTh9S
"""

class ContadorCaracter:
    """
    Clase que cuenta cuántas veces aparece un carácter específico
    en una cadena usando recursividad.
    """

    def __init__(self, cadena, caracter):
        """
        Inicializa la cadena y el carácter a buscar.
        :param cadena: str - Texto donde se buscará el carácter.
        :param caracter: str - Carácter a contar.
        """
        self.cadena = cadena
        self.caracter = caracter

    def contar(self, texto=None):
        """
        Método recursivo que cuenta las apariciones del carácter en la cadena.
        :param texto: str - Subcadena usada internamente durante la recursión.
        :return: int - Número de veces que aparece el carácter.
        """
        # Primera llamada: usar la cadena original
        if texto is None:
            texto = self.cadena

        # Caso base: cadena vacía
        if texto == "":
            return 0

        # Paso recursivo
        if texto[0] == self.caracter:
            return 1 + self.contar(texto[1:])
        else:
            return self.contar(texto[1:])

    def mostrar_resultado(self):
        """
        Muestra el resultado en pantalla de forma clara.
        """
        total = self.contar()
        print("\n==============================")
        print("  Conteo Recursivo de Carácter ")
        print("==============================")
        print(f"Cadena: '{self.cadena}'")
        print(f"Carácter buscado: '{self.caracter}'")
        print(f"Total de apariciones: {total}")
        print("==============================\n")


# ============================================
# EJECUCIÓN DEL PROGRAMA
# ============================================
if __name__ == "__main__":
    print("=== Contar carácter recursivamente ===")
    cadena = input("Ingrese una cadena: ")
    caracter = input("Ingrese el carácter a buscar: ")

    # Validar que solo se ingrese un carácter
    if len(caracter) != 1:
        print(" Error: Debe ingresar un solo carácter.")
    else:
        contador = ContadorCaracter(cadena, caracter)
        contador.mostrar_resultado()